name: Build Android
on: [workflow_call]
jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: build
        run: ./gradlew bundleReleaseAar assembleAccountReleaseXCFramework --parallel
