name: Push checks
on:
  push:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    uses: ./.github/workflows/build-android.yaml
  test:
    uses: ./.github/workflows/test-android.yaml
